name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
      - iam

  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass {0}

    steps:

      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          terraform_wrapper: false

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: ./prod
        run: terraform init

      # 5. Terraform Validate
      - name: Terraform Validate
        working-directory: ./prod
        run: terraform validate

      # 6. Terraform Plan
      - name: Terraform Plan
        working-directory: ./prod
        run: terraform plan  
