name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
      - iam

  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    steps:

      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CLIENT_ID }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      # 5. Terraform Init
      - name: Terraform Init
        shell: powershell
        working-directory: ./prod
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        shell: powershell
        working-directory: ./prod
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        shell: powershell
        working-directory: ./prod
        run: terraform plan -out=tfplan

      # 8. Upload Terraform Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: prod/tfplan
           # 9. Terraform Apply
      - name: Terraform Apply
        shell: powershell
        working-directory: ./prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
