name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
      - iam

  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    steps:

      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CLIENT_ID }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      # 5. Terraform Init
      - name: Terraform Init
        shell: powershell -ExecutionPolicy Bypass {0}
        working-directory: ./prod
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        shell: powershell -ExecutionPolicy Bypass {0}
        working-directory: ./prod
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        shell: powershell -ExecutionPolicy Bypass {0}
        working-directory: ./prod
        run: terraform plan -out=tfplan



